/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/aj_portfolio.glb -o app/AjModel.tsx --types 
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, OrthographicCamera, useAnimations, useTexture } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

export type ActionName = 'ThumbsUp' | 'BreathingIdle' | 'WavingGesture'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Boy01_Brows_Geo: THREE.SkinnedMesh
    Boy01_Eyes_Geo: THREE.SkinnedMesh
    Boy01_Body_Geo: THREE.SkinnedMesh
    h_Geo: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Boy01_Brows_MAT2: THREE.MeshStandardMaterial
    Boy01_Eyes_MAT2: THREE.MeshStandardMaterial
    Boy01_Body_MAT1: THREE.MeshStandardMaterial
    Boy01_Mouth_MAT2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type AjModelProps = JSX.IntrinsicElements['group'] & {
  animation?: ActionName
}

export function AjModel({ animation = 'BreathingIdle', ...props }: AjModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/aj_portfolio.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

  // Load textures
  const [diffuse, normal, spec, facialMap] = useTexture([
    '/textures/Boy01_diffuse.jpg',
    '/textures/Boy01_normal.jpg',
    '/textures/Boy01_spec.jpg',
    '/textures/Boy01_FacialAnimMap.png',
  ])

  // Fix mapping for glTF coordinates
  useEffect(() => {
    if (diffuse && normal && spec && facialMap) {
      [diffuse, normal, spec, facialMap].forEach((t) => {
        t.flipY = false
      })
      
      diffuse.colorSpace = THREE.SRGBColorSpace
      facialMap.colorSpace = THREE.SRGBColorSpace
      normal.colorSpace = THREE.NoColorSpace
      spec.colorSpace = THREE.NoColorSpace
    }
  }, [diffuse, normal, spec, facialMap])

  // Handle Animation Switching
  useEffect(() => {
    if (!actions || !actions[animation]) return

    // Fade out all currently playing animations
    Object.values(actions).forEach((action) => {
      if (action && action.isRunning()) {
        action.fadeOut(0.5)
      }
    })

    // Fade in and play the requested animation
    const currentAction = actions[animation]
    if (currentAction) {
      // Slow down BreathingIdle for a more 'zen' premium feel
      if (animation === 'BreathingIdle') {
        currentAction.setEffectiveTimeScale(0.8) // 20% slower
      } else {
        currentAction.setEffectiveTimeScale(1.0) // Normal speed for others
      }
      
      currentAction.reset().fadeIn(0.5).play()
    }

  }, [actions, animation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group position={[0, -92.624, 3.021]}>
          <primitive object={nodes.mixamorigHips} />
          <OrthographicCamera name="bottom" makeDefault={false} far={10} near={0} position={[0, -1000.1, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
          
          {/* Main Body Skin & Clothes */}
          <skinnedMesh 
            name="Boy01_Body_Geo" 
            geometry={nodes.Boy01_Body_Geo.geometry} 
            skeleton={nodes.Boy01_Body_Geo.skeleton}
          >
            <meshStandardMaterial 
              map={diffuse} 
              normalMap={normal} 
              roughnessMap={spec}
              roughness={0.8}
              metalness={0.1}
            />
          </skinnedMesh>

          {/* Brows */}
          <skinnedMesh 
            name="Boy01_Brows_Geo" 
            geometry={nodes.Boy01_Brows_Geo.geometry} 
            skeleton={nodes.Boy01_Brows_Geo.skeleton}
          >
            <meshStandardMaterial 
              map={facialMap} 
              transparent 
              alphaTest={0.5}
            />
          </skinnedMesh>
          
          {/* Eyes */}
          <skinnedMesh 
            name="Boy01_Eyes_Geo" 
            geometry={nodes.Boy01_Eyes_Geo.geometry} 
            skeleton={nodes.Boy01_Eyes_Geo.skeleton}
          >
            <meshStandardMaterial 
              map={facialMap} 
              transparent 
              alphaTest={0.5}
              roughness={0.1} 
              metalness={0.5} 
            />
          </skinnedMesh>
          
          {/* Mouth/Inside */}
          <skinnedMesh 
            name="h_Geo" 
            geometry={nodes.h_Geo.geometry} 
            skeleton={nodes.h_Geo.skeleton}
          >
            <meshStandardMaterial 
              map={facialMap} 
              transparent 
              alphaTest={0.5}
            />
          </skinnedMesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/aj_portfolio.glb')
