/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/aj_portfolio.glb -o app/AjModel.tsx --types
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useImperativeHandle, forwardRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

export type ActionName = 'ThumbsUp' | 'BreathingIdle' | 'WavingGesture'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Boy01_Brows_Geo: THREE.SkinnedMesh
    Boy01_Eyes_Geo: THREE.SkinnedMesh
    Boy01_Body_Geo: THREE.SkinnedMesh
    h_Geo: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Boy01_Brows_MAT2: THREE.MeshStandardMaterial
    Boy01_Eyes_MAT2: THREE.MeshStandardMaterial
    Boy01_Body_MAT1: THREE.MeshStandardMaterial
    Boy01_Mouth_MAT2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export interface AjModelHandle {
  playAnimation: (name: ActionName) => void
}

type AjModelProps = Omit<React.JSX.IntrinsicElements['group'], 'ref'>

export const AjModel = forwardRef<AjModelHandle, AjModelProps>(function AjModel(props, ref) {
  const group = useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/aj_portfolio.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  // Track which action is currently playing
  const currentActionRef = useRef<THREE.AnimationAction | null>(null)

  // Load textures
  const [diffuse, normal, spec, facialMap] = useTexture([
    '/textures/Boy01_diffuse.jpg',
    '/textures/Boy01_normal.jpg',
    '/textures/Boy01_spec.jpg',
    '/textures/Boy01_FacialAnimMap.png',
  ])

  // Fix texture coordinate mapping for glTF
  useEffect(() => {
    if (diffuse && normal && spec && facialMap) {
      ;[diffuse, normal, spec, facialMap].forEach((t) => { t.flipY = false })
      diffuse.colorSpace = THREE.SRGBColorSpace
      facialMap.colorSpace = THREE.SRGBColorSpace
      normal.colorSpace = THREE.NoColorSpace
      spec.colorSpace = THREE.NoColorSpace
    }
  }, [diffuse, normal, spec, facialMap])

  // Start BreathingIdle once actions are ready
  useEffect(() => {
    if (!actions?.BreathingIdle) return
    const idle = actions.BreathingIdle
    idle.setEffectiveTimeScale(0.8)
    idle.reset().fadeIn(0.4).play()
    currentActionRef.current = idle
  }, [actions])

  // Imperative API — bypasses React state/re-renders entirely
  useImperativeHandle(ref, () => ({
    playAnimation: (name: ActionName) => {
      if (!actions?.[name]) return
      const newAction = actions[name]!
      const current = currentActionRef.current

      // Don't restart the same animation
      if (current === newAction && newAction.isRunning()) return

      newAction.setEffectiveTimeScale(name === 'BreathingIdle' ? 0.8 : 1.0)

      if (current && current.isRunning()) {
        // Smooth crossfade: don't reset() — it calls stopFading() which zeroes weight
        newAction.enabled = true
        newAction.time = 0
        current.crossFadeTo(newAction, 0.4, false)
        newAction.play()
      } else {
        newAction.reset().fadeIn(0.4).play()
      }

      currentActionRef.current = newAction
    },
  }), [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group position={[0, -92.624, 3.021]}>
          <primitive object={nodes.mixamorigHips} />

          <skinnedMesh
            name="Boy01_Body_Geo"
            geometry={nodes.Boy01_Body_Geo.geometry}
            skeleton={nodes.Boy01_Body_Geo.skeleton}
          >
            <meshStandardMaterial
              map={diffuse}
              normalMap={normal}
              roughnessMap={spec}
              roughness={0.8}
              metalness={0.1}
            />
          </skinnedMesh>

          <skinnedMesh
            name="Boy01_Brows_Geo"
            geometry={nodes.Boy01_Brows_Geo.geometry}
            skeleton={nodes.Boy01_Brows_Geo.skeleton}
          >
            <meshStandardMaterial map={facialMap} transparent alphaTest={0.5} />
          </skinnedMesh>

          <skinnedMesh
            name="Boy01_Eyes_Geo"
            geometry={nodes.Boy01_Eyes_Geo.geometry}
            skeleton={nodes.Boy01_Eyes_Geo.skeleton}
          >
            <meshStandardMaterial
              map={facialMap}
              transparent
              alphaTest={0.5}
              roughness={0.1}
              metalness={0.5}
            />
          </skinnedMesh>

          <skinnedMesh
            name="h_Geo"
            geometry={nodes.h_Geo.geometry}
            skeleton={nodes.h_Geo.skeleton}
          >
            <meshStandardMaterial map={facialMap} transparent alphaTest={0.5} />
          </skinnedMesh>
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/aj_portfolio.glb')
